development:
  secret_key_base: c597b094b898d26d71da0135845bea79515287e4a41e2290d0c385c97051aeb2ad069fff114f3bbf88a2ae47cfdf32d1f6d4b1732dacd6752c7fca496dac5fcd

test:
  secret_key_base: a8c0b780072187b311ec96a7373aafe209eb57b10d08b1882ea2ced69d40a4aea7a2124bef379fa7b36e45a2abd48b62509fb5be98d4b76840a42f4406f66f24

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
